<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Empleados</title>
    </head>
    <body>
        <table border="1">
            <tr>
                <td colspan="4">
                  
                    <form class="" action="" method="post">
                        Ingrese mail:<input type="text" name="email" value="<?=$email;?>"><input type="submit" name="send" value="Buscar">
                    </form>
                </td>

            </tr>
            <tr>
                <td>Nombre</td>
                <td>Email</td>
                <td>Posición</td>
                <td>Salario</td>
                <td>Opcion</td>
            </tr>
        <?php
        foreach ($a_employees as $employee) {
            //print_r($this);?>
            <tr>
                <td><?=$employee['name'];?></td>
                <td><?=$employee['email'];?></td>
                <td><?=$employee['position'];?></td>
                <td><?=$employee['salary'];?></td>
                <td><a href="<?=$ruta->pathFor('viewDetail', ['id' => $employee['id'] ]);?>">Ver detalle</a></td>
            </tr>

            <?php
        }
        ?>
        </table>
    </body>
</html>
